### PR TITLE
[67] Fix custom image base64 conversion

### LINKED ISSUE #67: Fix custom image base64 conversion
**Steps to reproduce**
- Go to debate conf
- Open console 
- Select a custom branding image
- Select a large file
- Go to debate clock view
- Notice an error pop up in console and the _Loading..._ text be displayed indefinitely

### PR DESCRIPTION
**Pull request by Mateusz-Dobrzynski**
Closes #67.

From what I've inferred, the issue was caused by the array buffer exceeding the range that `String.fromCharCode()` could handle. This, however, doesn't explain why some smaller images couldn't be converted, while other bigger ones could. Either way, it works now, even with larger files (tested manually with 6K images).

Additionaly, the "Loading…" text is now in the middle of the clock, instead of being shifted to the side (it was caused by the fact that the image wasn't loaded, but it was already occupying space next to the text).

### CODE REVIEW

**Comment by jakubmanczak** [comment]
The preview shows a spam of Chrome warnings about some soon-to-be deprecated feature. Need to inspect that.

File: src/lib/imageToBase64.ts [hunk 1]
```diff
@@ -15,4 +19,4 @@ const convertImageToBase64 = (file: File): Promise<string> => {
     });
 };
 
-export { convertImageToBase64 };
\ No newline at end of file
+export { convertImageToBase64 }
```
Comment (jakubmanczak) [inline src/lib/imageToBase64.ts:22]: Why?
```suggestion
export { convertImageToBase64 };
```

**Review by jakubmanczak — APPROVED** [review]
🔥🔥🔥🔥
